name: Deploy function 'error-report' To Google Cloud Functions

on:
  push:
    paths:
      - 'src/functions/error-report/**'
      - '.github/workflows/deploy-error-report.yml'

jobs:
  deploy-function:
    name: Deploy To Google Cloud Functions
    runs-on: ubuntu-20.04
    timeout-minutes: 300
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - id: auth-gcloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
          create_credentials_file: true
          cleanup_credentials: true
      
      - id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: error-report
          runtime: python39
          entry_point: handler
          memory_mb: 512
          region: ${{ secrets.GCP_REGION }}
          env_vars: >-
            SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
          source_dir: src/functions/error-report
          timeout: 300
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ secrets.GCP_PROJECT_ID }}/topics/${{ secrets.ERROR_REPORT_TOPIC }}
          event_trigger_service: pubsub.googleapis.com
